# Generated by Django 5.2.5 on 2025-08-20 23:01

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('installation_date', models.DateTimeField(blank=True, null=True)),
                ('manufactured_date', models.DateTimeField(blank=True, null=True)),
                ('commission_date', models.DateTimeField(blank=True, null=True)),
                ('decommission_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('health', models.IntegerField(default=core.models.random_health)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('model_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_volume', models.FloatField(blank=True, null=True)),
                ('diameter', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'asset_types',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operational_since', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='AssetEvents',
            fields=[
                ('event_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('event_type_id', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.asset')),
            ],
            options={
                'db_table': 'asset_events',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.content'),
        ),
        migrations.AddField(
            model_name='asset',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.farm'),
        ),
        migrations.AddField(
            model_name='farm',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='core.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.material'),
        ),
    ]
