# Generated by Django 5.2.5 on 2025-08-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_eventtype_remove_assetevents_event_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='farm_models/'),
        ),
        migrations.AddField(
            model_name='farm',
            name='model_file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='model_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
