# Generated by Django 5.2.5 on 2025-08-21 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_farm_model_file_farm_model_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name (e.g., 'Standard Fixed Roof Tank')", max_length=100)),
                ('model_file', models.FileField(help_text='3D model file (.glb format)', upload_to='model_categories/')),
                ('is_default', models.BooleanField(default=False, help_text='Default model for this asset type')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.assettype')),
            ],
            options={
                'db_table': 'asset_models',
                'unique_together': {('asset_type', 'is_default')},
            },
        ),
    ]
