# Generated by Django 5.2.5 on 2025-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assetmodel'),
    ]

    operations = [
        # Add asset model fields
        migrations.AddField(
            model_name='asset',
            name='model_file',
            field=models.FileField(blank=True, help_text='3D model file (.glb format) for this specific asset', null=True, upload_to='asset_models/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_file_name',
            field=models.CharField(blank=True, help_text='Original filename of the 3D model', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        
        # Rename farm fields to be clearer
        migrations.RenameField(
            model_name='farm',
            old_name='model_file',
            new_name='site_model_file',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='model_file_name',
            new_name='site_model_file_name',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='model_uploaded_at',
            new_name='site_model_uploaded_at',
        ),
        
        # Add farm layout PDF field
        migrations.AddField(
            model_name='farm',
            name='layout_pdf',
            field=models.FileField(blank=True, help_text='2D farm layout diagram (PDF format)', null=True, upload_to='farm_layouts/'),
        ),
        
        # Update upload path for site model
        migrations.AlterField(
            model_name='farm',
            name='site_model_file',
            field=models.FileField(blank=True, help_text='3D site model showing overall farm layout (.glb format)', null=True, upload_to='farm_site_models/'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='site_model_file_name',
            field=models.CharField(blank=True, help_text='Original filename of the site model', max_length=255, null=True),
        ),
    ]
