# Generated by Django 5.2.5 on 2025-08-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_asset_and_farm_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model_file_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='layout_pdf',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='site_model_file',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='site_model_file_name',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='site_model_uploaded_at',
        ),
        migrations.DeleteModel(
            name='AssetModel',
        ),
    ]
